### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by adreena** [udacity/CarND-Mercedes-SF-Utilities#2]
+ Please fix the file names, and also provide a better readme . 
+ I wasn't sure if there's an order to run the files and what each notebook is supposed to display. 
+ py.iplot don't display anything, is there a specific version or python to use?
+ no requirements.txt

**Comment by nicholas-tien** [comment]
Hello,I have a question.In the data_generator_bicycle.m file,I think the 48th line "GT(8,k) = timestamp;" is wrong.it it should be "GT(4,k) = timestamp;" since GT is a 5 by nz matrix.

**Comment by RobinCPC** [comment]
I think you need `plotly` and `pandas` to get the figures on jupyter.
In additional, you could view those figures in ipynb file on nbviewer (without installing plotly and pandas). 
Here's the [link](https://nbviewer.jupyter.org/github/udacity/CarND-Mercedes-SF-Utilities/tree/master/python/)

**Comment by mvirgo** [comment]
Merged in @RobinCPC's PR to help here.
