### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mohamednour98** [udacity/CarND-Mercedes-SF-Utilities#4]
i think i need help with making new data i want to change path but its hard for me to understand all the yaw and yaw rate functions

**Comment by UAnjali** [comment]
Hi @mohamednour98 
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime in and new students can also learn from the discussion thread. 
Thank you
